FROM mysql:latest

SHELL ["/bin/bash", "-c"]

RUN ulimit -n 65536

RUN ulimit -u 4096

COPY docker/v1/init.sql.sh /docker-entrypoint-initdb.d/

COPY ./docker/v1/db-healthcheck.sh /usr/local/bin/healthcheck.sh

RUN chmod +x /usr/local/bin/healthcheck.sh
