FROM nginx:alpine

RUN apk update && apk add bash

SHELL ["/bin/bash", "-c"]

RUN ulimit -n 65536

RUN ulimit -u 4096

COPY docker/v1/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
