FROM node:lts-alpine

RUN apk update && apk add bash

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY package*.json ./

COPY tsconfig*.json ./

COPY src ./src

COPY libs ./libs

RUN npm install;npm run devBuild

EXPOSE 11758
#CMD ["tail", "-f", "/dev/null"]
CMD ["npm","run","start"]

