FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

COPY tsconfig*.json ./

COPY src ./src

RUN npm install;npm run devBuild

EXPOSE 11758
#CMD ["tail", "-f", "/dev/null"]
CMD ["npm","run","start"]

