name: 50-Device Concurrent WebSocket Messaging stress test
on: 
  push:
    branches: [ feat/api-ws-tests ]
  workflow_dispatch:

jobs:
  load-test-with-docker:
    runs-on: ubuntu-latest
    environment: load_test
    strategy:
      fail-fast: false
      matrix:
        WS_MSG_INTERVAL: [100, 200, 300, 400, 500]
    timeout-minutes: 10 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DATABASE_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWD }}" >> .env
          echo "DATABASE_USER=${{ secrets.DB_USER }}" >> .env
          echo "DATABASE_USER_PASSWORD=${{ secrets.DB_USER_PASSWD }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DATABASE_HOST=mysql" >> .env
          echo "DATABASE_PORT=3306" >> .env
          mkdir -p docker/v1
          mv .env docker/v1/

      - name: Start Services
        run: docker compose -f ./docker/v1/docker-compose.yml up -d

      - name: Wait for Services to be Ready
        run: |
          sleep 15
          curl --retry 5 --retry-connrefused http://localhost:8883/health

      - name: Setup Grafana K6
        uses: grafana/setup-k6-action@v1

      - name: Execute Test
        id: k6_run
        run: |
          k6 run load-main-test.js --summary-export=../../summary.json
        working-directory: ./tests/src 
        env:
          WS_MSG_INTERVAL: ${{ matrix.WS_MSG_INTERVAL }}

      - name: Get Devices Count
        env:
          MYSQL_PWD: "${{secrets.DB_ROOT_PASSWD}}"
        run: |
          docker exec -e MYSQL_PWD mysql mysql \
            -u root \
            -e "SELECT COUNT(*) FROM ${{secrets.DB_NAME}}.devices;"

      - name: Extract k6 WS Messages Sent
        id: k6_stats
        run: |
          WS_SENT=$(jq '.metrics.ws_metrics_sent_msgs.values.count' summary.json)
          echo "WS_SENT=$WS_SENT" >> $GITHUB_ENV
          echo "K6 sent $WS_SENT message batches"

      - name: Get Log Messages Count
        env:
          MYSQL_PWD: "${{secrets.DB_ROOT_PASSWD}}"
        run: |
          ROW_COUNT=$(docker exec -e MYSQL_PWD mysql mysql -u root -N -s -e "SELECT COUNT(*) FROM ${{secrets.DB_NAME}}.device_monitor_log;" | awk '{print $1}')
          echo "ROW_COUNT=$ROW_COUNT" >> $GITHUB_ENV
          echo "$ROW_COUNT rows found in database."

      - name: Compare and Validate
        run: |
          if [[ -z "$WS_SENT" || "$WS_SENT" == "null" || -z "$ROW_COUNT" ]]; then
            echo "::error::Metrics missing. K6: $WS_SENT, DB: $ROW_COUNT"
            exit 1
          fi

          EXPECTED_ROWS=$(( WS_SENT * 4 ))

          echo "K6 Messages Sent: $WS_SENT"
          echo "Expected Rows ($WS_SENT * 4): $EXPECTED_ROWS"
          echo "Actual Rows in MySQL: $ROW_COUNT"

          if [ "$ROW_COUNT" -lt "$EXPECTED_ROWS" ]; then
            echo "::error::Data integrity check failed! Expected at least $EXPECTED_ROWS rows but found $ROW_COUNT."
            exit 1
          else
            echo "Success: Data counts match or exceeded minimum requirement."
          fi

      - name: Stop Services
        if: always()
        run: docker compose -f ./docker/v1/docker-compose.yml down -v